# Generated by Django 5.0.7 on 2026-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('preparing', '备餐中'), ('delivering', '配送中'), ('completed', '已完成'), ('abnormal', '异常'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
